# Generated by Django 5.2.14 on 2026-05-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shelf_images/')),
                ('posm_ok', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('synced', 'Synced'), ('gps_flagged', 'GPS Flagged')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='outlets.outlet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
