# Generated by Django 5.2.14 on 2026-06-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_blurry', models.BooleanField(default=False)),
                ('is_gps_flagged', models.BooleanField(default=False)),
                ('is_timestamp_bad', models.BooleanField(default=False)),
                ('is_fraud', models.BooleanField(default=False)),
                ('duplicate_detail', models.TextField(blank=True, default='')),
                ('blur_detail', models.TextField(blank=True, default='')),
                ('gps_detail', models.TextField(blank=True, default='')),
                ('timestamp_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_log', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
