# Generated by Django 5.2.14 on 2026-06-12 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_count', models.IntegerField(default=0)),
                ('competitor_count', models.IntegerField(default=0)),
                ('compliance_score', models.FloatField(default=0.0)),
                ('supervisor_summary', models.TextField(blank=True, default='')),
                ('raw_response', models.TextField(blank=True, default='')),
                ('analysis_successful', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_analysis', to='visits.visit')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
