from django.db import models
from visits.models import Visit


class ShelfAnalysis(models.Model):
    """
    Stores the result of an AI shelf analysis for one visit.

    OneToOneField because one visit has at most one analysis result.
    If the supervisor wants a fresh analysis, we update the existing one
    (using update_or_create, same pattern as FraudLog).
    """
    visit = models.OneToOneField(
        Visit,
        on_delete=models.CASCADE,
        related_name='shelf_analysis'
    )

    # Product counts returned by Gemini
    our_count         = models.IntegerField(default=0)
    competitor_count  = models.IntegerField(default=0)

    # Compliance score: our_count / (our_count + competitor_count) * 100
    # Stored as a float 0.0 - 100.0
    compliance_score  = models.FloatField(default=0.0)

    # Natural language summary generated by Gemini
    supervisor_summary = models.TextField(blank=True, default='')

    # Raw response from Gemini (useful for debugging)
    raw_response = models.TextField(blank=True, default='')

    # Whether the AI call succeeded or fell back to defaults
    analysis_successful = models.BooleanField(default=False)

    analyzed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-analyzed_at']

    def __str__(self):
        return (
            f"Analysis for Visit {self.visit_id} — "
            f"{self.compliance_score:.1f}% compliance"
        )